<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="E:\Work\repositories\Authentication\tests\Chaos.Portal.Authentication.Test.dll" total="43" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2015-03-15" time="00:41:47">
  <environment nunit-version="2.6.0.12051" clr-version="2.0.50727.8009" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="E:\Work\repositories\Authentication\tests" machine-name="BASEMENT-00" user="JesperFyhr" user-domain="BASEMENT-00" />
  <culture-info current-culture="da-DK" current-uiculture="en-US" />
  <test-suite type="Assembly" name="E:\Work\repositories\Authentication\tests\Chaos.Portal.Authentication.Test.dll" executed="True" result="Success" success="True" time="1.454" asserts="0">
    <results>
      <test-suite type="Namespace" name="Chaos" executed="True" result="Success" success="True" time="1.442" asserts="0">
        <results>
          <test-suite type="Namespace" name="Portal" executed="True" result="Success" success="True" time="1.441" asserts="0">
            <results>
              <test-suite type="Namespace" name="Authentication" executed="True" result="Success" success="True" time="1.441" asserts="0">
                <results>
                  <test-suite type="Namespace" name="Tests" executed="True" result="Success" success="True" time="1.441" asserts="0">
                    <results>
                      <test-suite type="TestFixture" name="AuthenticationModuleTest" executed="True" result="Success" success="True" time="0.530" asserts="0">
                        <results>
                          <test-case name="Chaos.Portal.Authentication.Tests.AuthenticationModuleTest.Load_Extensions_AllExtensionsWereMapped" executed="True" result="Success" success="True" time="0.489" asserts="0" />
                          <test-case name="Chaos.Portal.Authentication.Tests.AuthenticationModuleTest.Load_ValidConfiguration" executed="True" result="Success" success="True" time="0.003" asserts="0" />
                          <test-case name="Chaos.Portal.Authentication.Tests.AuthenticationModuleTest.OnUserInfoUpdate_GivenInfo_ShouldInvokeListener" executed="True" result="Success" success="True" time="0.021" asserts="3" />
                          <test-case name="Chaos.Portal.Authentication.Tests.AuthenticationModuleTest.OnUserInfoUpdate_GivenInfo_ShouldNotInvokeListenerWithDifferentType" executed="True" result="Success" success="True" time="0.004" asserts="1" />
                        </results>
                      </test-suite>
                      <test-suite type="Namespace" name="Domain" executed="True" result="Success" success="True" time="0.208" asserts="0">
                        <results>
                          <test-suite type="TestFixture" name="PasswordHelperTest" executed="True" result="Success" success="True" time="0.208" asserts="0">
                            <results>
                              <test-case name="Chaos.Portal.Authentication.Tests.Domain.PasswordHelperTest.GenerateHash_MultipleIterationWithoutSalt_ShouldGenerateDifferentHashesForSamePassword" executed="True" result="Success" success="True" time="0.200" asserts="3" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Domain.PasswordHelperTest.GenerateHash_OneIterationWithoutSalt_DifferentSaltsYieldSameResult" executed="True" result="Success" success="True" time="0.002" asserts="2" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Domain.PasswordHelperTest.GenerateHash_OneIterationWithoutSalt_ShouldBeCompatibleWithV5" executed="True" result="Success" success="True" time="0.002" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Domain.PasswordHelperTest.GenerateHash_OneIterationWithSalt_ShouldGenerateDifferentHashesForSamePassword" executed="True" result="Success" success="True" time="0.003" asserts="3" />
                            </results>
                          </test-suite>
                        </results>
                      </test-suite>
                      <test-suite type="Namespace" name="Extension" executed="True" result="Success" success="True" time="0.555" asserts="0">
                        <results>
                          <test-suite type="TestFixture" name="AuthKeyTest" executed="True" result="Success" success="True" time="0.099" asserts="0">
                            <results>
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.AuthKeyTest.Create_GivenAnonymousUser_ThrowException" executed="True" result="Success" success="True" time="0.018" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.AuthKeyTest.Create_GivenSiteDoesntExist_ReturnSiteKey" executed="True" result="Success" success="True" time="0.024" asserts="2" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.AuthKeyTest.Create_UnknownErrorOnDatabase_ThrowException" executed="True" result="Success" success="True" time="0.006" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.AuthKeyTest.Delete_GivenExistingAuthKey_DeleteKeyReturnOne" executed="True" result="Success" success="True" time="0.010" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.AuthKeyTest.Delete_GivenNonExistingAuthKey_ThrowArgumentException" executed="True" result="Success" success="True" time="0.006" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.AuthKeyTest.Get_UserhasAuthKeys_ReturnListOfAuthKeysWithOutTokens" executed="True" result="Success" success="True" time="0.011" asserts="2" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.AuthKeyTest.Get_UserHasNoAuthKeys_ReturnEmptyList" executed="True" result="Success" success="True" time="0.007" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.AuthKeyTest.Login_InvalidApiKey_ThrowException" executed="True" result="Success" success="True" time="0.006" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.AuthKeyTest.Login_ValidApiKey_ReturnAuthenticatedSession" executed="True" result="Success" success="True" time="0.007" asserts="1" />
                            </results>
                          </test-suite>
                          <test-suite type="TestFixture" name="EmailPasswordTests" executed="True" result="Success" success="True" time="0.048" asserts="0">
                            <results>
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.EmailPasswordTests.Login_GivenInvalidEmail_ThrowsLoginException" executed="True" result="Success" success="True" time="0.006" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.EmailPasswordTests.Login_GivenValidEmailAndPassword_ReturnUserInfoAndAuthenticateSession" executed="True" result="Success" success="True" time="0.017" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.EmailPasswordTests.Login_GivenValidEmailAndWrongPassword_ThrowsLoginException" executed="True" result="Success" success="True" time="0.007" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.EmailPasswordTests.SetPassword_UserDoesNotHavePermission_ThrowInsufficientPermissionsException" executed="True" result="Success" success="True" time="0.004" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.EmailPasswordTests.SetPassword_UserHasPermission_UpdatePassword" executed="True" result="Success" success="True" time="0.011" asserts="1" />
                            </results>
                          </test-suite>
                          <test-suite type="TestFixture" name="FacebookTests" executed="True" result="Success" success="True" time="0.056" asserts="0">
                            <results>
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.FacebookTests.Login_InvalidSignedRequest_ThrowException" executed="True" result="Success" success="True" time="0.017" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.FacebookTests.Login_ProvidesSessionGuid_AuthenticateSessionProvided" executed="True" result="Success" success="True" time="0.013" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.FacebookTests.Login_ValidSignedRequestAndUserAlreadyExist_CreateAndReturnAnAuthenticatedSession" executed="True" result="Success" success="True" time="0.010" asserts="2" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.FacebookTests.Login_ValidSignedRequestAndUserDoesntExist_CreateUserAndReturnAuthenticatedSession" executed="True" result="Success" success="True" time="0.012" asserts="2" />
                            </results>
                          </test-suite>
                          <test-suite type="TestFixture" name="OAuthTest" executed="True" result="Success" success="True" time="0.037" asserts="0">
                            <results>
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.OAuthTest.GetLoginEndPoint_GivenCallbackUrl_ReturnEndPoint" executed="True" result="Success" success="True" time="0.005" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.OAuthTest.ProcessLogin_GivenNewValidOAuthLogin_ReturnAndAuthorizeSession" executed="True" result="Success" success="True" time="0.025" asserts="2" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.OAuthTest.ProcessLogin_GivenNewValidOAuthLoginWithoutIntranetAccess_ReturnAndAuthorizeSession" executed="True" result="Success" success="True" time="0.005" asserts="0" />
                            </results>
                          </test-suite>
                          <test-suite type="TestFixture" name="SecureCookieTests" executed="True" result="Success" success="True" time="0.073" asserts="0">
                            <results>
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.SecureCookieTests.Create_IsAuthenticated_CreateAndReturnSecureCookie" executed="True" result="Success" success="True" time="0.013" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.SecureCookieTests.Create_IsNotAuthenticated_ThrowLoginException" executed="True" result="Success" success="True" time="0.003" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.SecureCookieTests.Delete_GivenExistingSession_ReturnOne" executed="True" result="Success" success="True" time="0.006" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.SecureCookieTests.Get_GivenExistingSession_ReturnSecureCookie" executed="True" result="Success" success="True" time="0.006" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.SecureCookieTests.Login_GivenExistingCookie_UseCookieAndCreateANewOneAndAuthenticateSession" executed="True" result="Success" success="True" time="0.042" asserts="3" />
                            </results>
                          </test-suite>
                          <test-suite type="TestFixture" name="WayfTests" executed="True" result="Success" success="True" time="0.236" asserts="0">
                            <results>
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.WayfTests.Login_GivenExistingWayfId_ReturnUserInfoAndUpdateProfileAndAuthenticateSession" executed="True" result="Success" success="True" time="0.206" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.WayfTests.Login_GivenNoEmail_CreateUser" executed="True" result="Success" success="True" time="0.013" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.WayfTests.Login_GivenNotAllowedWayfUser_ThrowWayfUserNotAllowedException" executed="True" result="Success" success="True" time="0.012" asserts="0" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Extension.WayfTests.Login_MissingWayfId_ThrowLoginException" executed="True" result="Success" success="True" time="0.003" asserts="0" />
                            </results>
                          </test-suite>
                        </results>
                      </test-suite>
                      <test-suite type="Namespace" name="Wayf" executed="True" result="Success" success="True" time="0.139" asserts="0">
                        <results>
                          <test-suite type="TestFixture" name="WayfFilterTest" executed="True" result="Success" success="True" time="0.138" asserts="0">
                            <results>
                              <test-case name="Chaos.Portal.Authentication.Tests.Wayf.WayfFilterTest.Validate_GivenFileToLoad_ShouldLoadFilter" executed="True" result="Success" success="True" time="0.116" asserts="3" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Wayf.WayfFilterTest.Validate_GivenInvalidAttributes_ShouldReturnFalse" executed="True" result="Success" success="True" time="0.010" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Wayf.WayfFilterTest.Validate_GivenValidAttributes_ShouldReturnTrue" executed="True" result="Success" success="True" time="0.003" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Wayf.WayfFilterTest.Validate_GivenValidAttributesMathSecondFilterGroup_ShouldReturnTrue" executed="True" result="Success" success="True" time="0.002" asserts="1" />
                              <test-case name="Chaos.Portal.Authentication.Tests.Wayf.WayfFilterTest.Validate_GivenWayfTestAttributes_ShouldReturnTrue" executed="True" result="Success" success="True" time="0.004" asserts="1" />
                            </results>
                          </test-suite>
                        </results>
                      </test-suite>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>